from .advogado_services import *
from .cliente_services import *
from .processos_services import *
from .graficos_services import *
from .parceiros_services import *
from .tarefas_services import *
from .escritorio_services import *
from .documento_services import *
from .data_field_services import *
from .health_services import *