from .auth_views import *
from .advogados_views import *
from .processos_views import *
from .cliente_views import *
from .data_field_views import *
from .escritorios_views import *
from .graficos_views import *
from .pagination_views import *
from .tarefas_views import *
from .parceiros_views import *
from .documento_view import *
from .health_views import *
